#ascii values 
#ASCII stands for American Standard Code for Information Interchange.
#It maps characters (like 'A', 'b', '1', '@') to integer values from 0 to 127.
#A TO Z (65 TO 90)
#a to z (97 to 122)
#digits (0to9):- (48 to 57)


#chr()
# What it does: Converts an integer ASCII code (or Unicode code point) to its corresponding character.
# Input: Integer (e.g., 65)
# Output: Single-character string (e.g., 'A')
#exmaple
# print(chr(65))
#print(chr(114))

# ord()
# What it does: Converts a single character to its corresponding ASCII (or Unicode) integer code.
# Input: Single-character string (e.g., 'A')
# Output: Integer code (e.g., 65)
# print(ord('r')) #OP:-114
# print(ord('H')) #OP:-72



# a='l'
# b=ord(a)
# # if('A'<a<'Z'):
#     print("it is in uppercase")
#     cnvrt=b+32
#     print(chr(cnvrt),"converted to lowercase")
# elif('a'<a<'z'):
#     print("it is in lowercase")
#     cnvrt=b-32
#     print(chr(cnvrt),"cnvered to uppercase")
# else:
#     print("invalid character")

#ippudu nennu c ni istey D ravali +33
#alagey C istey b ravali -31

# ascii=input('enter a value=')
# py=ord(ascii) 
# y=py+34
# p=py-31
# if("a"<ascii<"z"):
#     print(chr(p))
# elif("A"<ascii<"Z"):
#     print(chr(y))
# else:
#     print('book ur tickets')

# a='r'
# b=ord(a)
# ab=b+32 # for converting uppercase to lowercase
# ba=b-32 # for converting lowercase to uppercase
# if('a'<a<'z'):
#     print(f'{chr(ba)} is captail of small r')
# elif("A"<a<"Z"):
#     print(f'{chr(ab)} cnvrt')
# else:
#     print('inka waste ra babu')



    
    

